In [1]:
import numpy as np

In [24]:
arr1 = np.array([1,2,0,3,4,5,0,5,6])
arr2 = np.array([1.01,2,0,3,4.05,5,0,5,6.01])
print(arr1.shape)
print(arr2.shape)

(9,)
(9,)


**    1-Write a NumPy program to test whether none of the elements of a given array is zero.**

In [3]:
arr1==0

array([False, False,  True, False, False, False,  True, False, False])

2-Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [4]:
arr1!=0

array([ True,  True, False,  True,  True,  True, False,  True,  True])

3-Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two
given arrays


In [28]:
print(np.allclose(arr1,arr2))
print(np.allclose(arr1,arr2,atol = 0.05))
print(np.allclose(arr1,arr2,atol = 0.001))

False
True
False


4- Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [5]:
arr1 = np.zeros(10)
arr2=np.ones(10)
arr3 = 5*np.ones(10)
arr4 = np.hstack((arr1, arr2))
arr5 = np.hstack((arr4, arr3))
arr5

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5-Write a NumPy program to create an array of the integers from 30 to70.

In [6]:
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

6.    Write a NumPy program to create a 3x3 identity matrix

In [7]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

7.    Write a NumPy program to generate a random number between 0 and 1

In [8]:
np.random.rand(1)

array([0.40129692])

8-Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution

In [9]:
np.random.rand(15)

array([0.04947652, 0.33320692, 0.97228371, 0.87852865, 0.64080846,
       0.29109182, 0.90333762, 0.20991174, 0.20421629, 0.54051462,
       0.85728197, 0.47847604, 0.30194864, 0.65289128, 0.01539319])

9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
except the first and last.

In [10]:
arr1 = np.arange(15,56)
arr1[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [11]:
np.random.randint(0,10,5)

array([3, 7, 6, 1, 6])

11-Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal
to 1, and inside 0.

In [12]:
arr1 = np.zeros([10,10])
arr1[0,:]=1
arr1[:,0]=1
arr1[-1,:]=1
arr1[:,-1]=1
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

12.Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
3, 4, 5.

In [13]:
arr1 = np.zeros([5,5])
for i in range(5):
    arr1[i, i] = i+1
arr1

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

13.Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main
diagonal.

In [14]:
arr1 = np.zeros([4,4])
arr1[1::2, ::2] = 1
arr1[::2, 1::2] = 1
arr1

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

14.  Write a NumPy program to save two given arrays into a single file in compressed format (.npz format)
and load it.

In [16]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

np.savez_compressed('file.npz', array1=arr1, array2=arr2)
data = np.load('file.npz')

newArr1 = data['array1']
newArr2 = data['array2']

print("Loaded Array 1:")
print(newArr1)

print("\nLoaded Array 2:")
print(newArr2)


Loaded Array 1:
[1 2 3 4]

Loaded Array 2:
[5 6 7 8]


15- Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.
Select

In [17]:
arr1 = np.random.rand(40)
arr1

array([0.92843202, 0.0455503 , 0.8800992 , 0.46396975, 0.03127444,
       0.80123557, 0.94769358, 0.08605074, 0.62947867, 0.84832361,
       0.01600977, 0.50295115, 0.28564597, 0.89455792, 0.43771703,
       0.44296581, 0.95260046, 0.79673009, 0.03741689, 0.28412938,
       0.26349964, 0.99110375, 0.22161732, 0.56610806, 0.75512717,
       0.6452718 , 0.32876905, 0.37427488, 0.54472688, 0.91501595,
       0.38087289, 0.30149768, 0.16674385, 0.09562185, 0.82015829,
       0.4725603 , 0.67932155, 0.48881392, 0.27483687, 0.43287266])

16. Write a NumPy program to extract all numbers from a given array which are less and greater than a
specified number.

In [20]:
x = int(input("Please enter a number: "))
arr1 = np.array([1,3,6,8,11,0,-2,-5,4,5,7,9,55,33,12,11,-221])
arr1[arr1>x]

Please enter a number: 4


array([ 6,  8, 11,  5,  7,  9, 55, 33, 12, 11])